spring.application.name=payment-process-week2-H2DB
server.port=8089


# DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/paymentdev
spring.datasource.username=root
spring.datasource.password=Bhagat
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#jwt.secret=MyVeryStrongSecretKeyForPaymentProcessingSystem2026JWTSecurity
#jwt.secret=R7N3qW9kT2xY8mLp4Vb6Hs1Jc5Df8ZaQnE2Rt7Uy0Iw=
 
#jwt.expiration=86400000